---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: boostrap-bionic
    box: ubuntu/bionic64
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      bootstrap-fedora:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: vagrant
